# Generated by Django 3.0.5 on 2020-04-28 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20200428_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='post.Post'),
        ),
    ]
