export const GET_AUTH_STATE = "GET_AUTH_STATE";
export const CONVERT_GOOGLE_TOKEN_SUCCESS = "CONVERT_GOOGLE_TOKEN_SUCCESS";
export const HANDLE_GOOGLE_LOGOUT = "HANDLE_GOOGLE_LOGOUT";
export const TOKEN_REFRESHING = "TOKEN_REFRESHING";
export const TOKEN_REFRESHED = "TOKEN_REFRESHED";

export const FETCH_SECRETS = "FETCH_SECRETS";

export const FETCH_USER_DETAILS_SUCCESS = "FETCH_USER_DETAILS_SUCCESS";
export const FETCH_USER_DETAILS_FAILURE = "FETCH_USER_DETAILS_FAILURE";
export const UPDATE_USER_DETAILS = "UPDATE_USER_DETAILS";
export const REMOVE_USER_DETAILS = "REMOVE_USER_DETAILS";
